// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIa7Az0JN8xg_DmGnRsj2k9h8OP0ubuaE',
    appId: '1:1091887943347:web:be9ebdbfaa55ea3a50eac6',
    messagingSenderId: '1091887943347',
    projectId: 'flutter-chat-app-12',
    authDomain: 'flutter-chat-app-12.firebaseapp.com',
    storageBucket: 'flutter-chat-app-12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbBbGiWxmf-kXB5UBuotmbueCWiWuh5w',
    appId: '1:1091887943347:android:07f20dcefda85f1350eac6',
    messagingSenderId: '1091887943347',
    projectId: 'flutter-chat-app-12',
    storageBucket: 'flutter-chat-app-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg-2deMZoQj9d_KgD3O-d6WDQUEgVt0YM',
    appId: '1:1091887943347:ios:d7d269a37b06fe9b50eac6',
    messagingSenderId: '1091887943347',
    projectId: 'flutter-chat-app-12',
    storageBucket: 'flutter-chat-app-12.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg-2deMZoQj9d_KgD3O-d6WDQUEgVt0YM',
    appId: '1:1091887943347:ios:64571c0f34ddf22d50eac6',
    messagingSenderId: '1091887943347',
    projectId: 'flutter-chat-app-12',
    storageBucket: 'flutter-chat-app-12.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
